apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-deployment
  labels:
    app: dogs
spec:
  selector:
    matchLabels:
      app: dogs
  replicas: 3
  template:
    metadata:
      labels:
        app: dogs
    spec:
      containers:
      - name: dog-container
        image: 459956101257.dkr.ecr.us-east-1.amazonaws.com/dog-repo:v0.2
        ports:
        - containerPort: 80
